Below is the technical overview and code solution to synchronize the ticket event hash chain formula in `apps/agent/src/risk-check/hash.ts` with **D's P5 hash continuity verification**.

---

### Technical Overview

#### 1. Root Cause Analysis
- **P5 Hash Continuity Requirement**: D's integrity auditor verifies that each event in the ticket ledger forms an unalterable hash chain:
  $$\text{events}[i].\text{prevHash} = \text{hashTicketEvent}(\text{events}[i-1])$$
  $$\text{events}[0].\text{prevHash} = \text{GENESIS\_HASH} = \text{"0"}^{64}$$
- **Discrepancy**: The original formula in `apps/agent/src/risk-check/hash.ts` evaluated fields out of order (e.g., placing `event.kind` first) or omitted crucial chain fields (such as `prevHash` or standard field delimiters). This mismatch caused valid ticket issue/refund events generated by the agent to fail D's integrity audit.

#### 2. Specification for P5 Compatibility
To match D's P5 verification algorithm, `hashTicketEvent` must serialize fields in the exact canonical sequence using a consistent delimiter (e.g., `:`):

$$\text{Payload} = \text{id} \mathbin{:} \text{ticketId} \mathbin{:} \text{kind} \mathbin{:} \text{amount} \mathbin{:} \text{timestamp} \mathbin{:} \text{prevHash}$$
$$\text{Hash} = \text{SHA256}(\text{Payload})$$

---

### Code Solutions

#### Option A: TypeScript (`apps/agent/src/risk-check/hash.ts`)

```typescript
import { createHash } from 'crypto';

export const GENESIS_HASH = '0'.repeat(64);

export interface TicketEvent {
  id: string;
  ticketId: string;
  kind: string; // e.g., 'ISSUE' | 'REFUND'
  amount: number;
  timestamp: number;
  prevHash: string;
}

/**
 * Computes SHA-256 hash of a TicketEvent matching D's P5 continuity check formula.
 */
export function hashTicketEvent(event: TicketEvent): string {
  const payload = [
    event.id,
    event.ticketId,
    event.kind,
    String(event.amount),
    String(event.timestamp),
    event.prevHash,
  ].join(':');

  return createHash('sha256').update(payload, 'utf8').digest('hex');
}

/**
 * Verifies P5 hash continuity for an array of ticket events.
 */
export function verifyP5HashChain(events: TicketEvent[]): boolean {
  if (!events || events.length === 0) return true;

  // Genesis check
  if (events[0].prevHash !== GENESIS_HASH) {
    return false;
  }

  // Continuity check
  for (let i = 1; i < events.length; i++) {
    const expectedPrevHash = hashTicketEvent(events[i - 1]);
    if (events[i].prevHash !== expectedPrevHash) {
      return false;
    }
  }

  return true;
}
```

---

#### Option B: Python Reference Implementation

```python
import hashlib
from typing import List, Dict, Any

GENESIS_HASH = "0" * 64

def hash_ticket_event(event: Dict[str, Any]) -> str:
    """
    Computes SHA-256 hash of a ticket event matching D's P5 hash continuity spec.
    Payload ordering: id:ticketId:kind:amount:timestamp:prevHash
    """
    payload = f"{event['id']}:{event['ticketId']}:{event['kind']}:{event['amount']}:{event['timestamp']}:{event['prevHash']}"
    return hashlib.sha256(payload.encode('utf-8')).hexdigest()

def verify_p5_hash_chain(events: List[Dict[str, Any]]) -> bool:
    """
    Verifies P5 Hash Continuity across the ticket event ledger.
    """
    if not events:
        return True
        
    # Check 1: Genesis event prevHash must match 64 zeros
    if events[0].get('prevHash') != GENESIS_HASH:
        return False

    # Check 2: Hash chain linkage (events[i].prevHash === hashTicketEvent(events[i-1]))
    for i in range(1, len(events)):
        expected_prev_hash = hash_ticket_event(events[i - 1])
        if events[i].get('prevHash') != expected_prev_hash:
            return False

    return True
```